version: "3"
services:
  api:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "3316:3306"
  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
    init: true
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  postgres_data:
  bundle: